### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by KingRainbow44** [KingRainbow44/WooMinecraft-PM#1]
- [ ] Create all the folders and files of WooMinecraft
- [ ] Start on WooCommand
- [ ] Start on WooMinecraft
- [ ] Start on the payment task
- [ ] Start on linking WooCommerence to WooMinecraft
- [ ] Copy WooMinecraft and think about the similarities to PHP and Java
